// Generated by gencpp from file station_control/controlCamera.msg
// DO NOT EDIT!


#ifndef STATION_CONTROL_MESSAGE_CONTROLCAMERA_H
#define STATION_CONTROL_MESSAGE_CONTROLCAMERA_H

#include <ros/service_traits.h>


#include <station_control/controlCameraRequest.h>
#include <station_control/controlCameraResponse.h>


namespace station_control
{

struct controlCamera
{

typedef controlCameraRequest Request;
typedef controlCameraResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct controlCamera
} // namespace station_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::station_control::controlCamera > {
  static const char* value()
  {
    return "b22a4a9b6885ed559627c00f9ea190ce";
  }

  static const char* value(const ::station_control::controlCamera&) { return value(); }
};

template<>
struct DataType< ::station_control::controlCamera > {
  static const char* value()
  {
    return "station_control/controlCamera";
  }

  static const char* value(const ::station_control::controlCamera&) { return value(); }
};


// service_traits::MD5Sum< ::station_control::controlCameraRequest> should match
// service_traits::MD5Sum< ::station_control::controlCamera >
template<>
struct MD5Sum< ::station_control::controlCameraRequest>
{
  static const char* value()
  {
    return MD5Sum< ::station_control::controlCamera >::value();
  }
  static const char* value(const ::station_control::controlCameraRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::station_control::controlCameraRequest> should match
// service_traits::DataType< ::station_control::controlCamera >
template<>
struct DataType< ::station_control::controlCameraRequest>
{
  static const char* value()
  {
    return DataType< ::station_control::controlCamera >::value();
  }
  static const char* value(const ::station_control::controlCameraRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::station_control::controlCameraResponse> should match
// service_traits::MD5Sum< ::station_control::controlCamera >
template<>
struct MD5Sum< ::station_control::controlCameraResponse>
{
  static const char* value()
  {
    return MD5Sum< ::station_control::controlCamera >::value();
  }
  static const char* value(const ::station_control::controlCameraResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::station_control::controlCameraResponse> should match
// service_traits::DataType< ::station_control::controlCamera >
template<>
struct DataType< ::station_control::controlCameraResponse>
{
  static const char* value()
  {
    return DataType< ::station_control::controlCamera >::value();
  }
  static const char* value(const ::station_control::controlCameraResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // STATION_CONTROL_MESSAGE_CONTROLCAMERA_H
